[parameters]
mac_address = 9BFF04BEE

; language options: english, japanese, french, italian, german, spanish, korean
language = english

; version options: black, white, black_2, white_2
version = white_2

; search types: iv, iv_pokerus, trainer_skip, plasma_skip
search_type = trainer_skip

[search.ivs]
hp_iv_range 	= 31, 31
atk_iv_range 	= 31, 31
def_iv_range 	= 31, 31
spatk_iv_range 	= 0, 31
spdef_iv_range 	= 31, 31
speed_iv_range 	= 31, 31

[search.pkrs]
pkrs_frame_range = 2900, 3200

[search.trainer_skip]
; start options:
;  - default: inside the humilau gym
;  - x, y: coordinates humilau city
start = default

[search.plasma_skip]

[parameters.date_time]
; Filters out specific dates depending on the game version
;
; black/white applies the following date filters:
; - Exclusively search winter months
; - Ignore dates with Hail
;
; black_2/white_2 applies the following date filters:
; - Ignore summer months
; - Ignore dates with Rain or Hail in:
; 	- Flocessy Town / Route 20
; 	- Virbank City
; 	- Driftveil City / Route 6
;
; For more information, see: 
; 	- bw1: https://web.archive.org/web/20230319002112/http://wiki.pokemonspeedruns.com/index.php/Pok%C3%A9mon_Black/White/Winter_weather
; 	- bw2: https://docs.google.com/spreadsheets/d/16WCOVv80hkMrcXyQPorrgBBRBjsLQcq8q7N4VxnDewo
use_speedrun_filters = true

year_range = 2000, 2099
month_range = 1, 12
day_range = 1, 31

hour_range = 0, 23
minute_range = 0, 59
second_range = 5, 5

[parameters.misc]
timer0_range = 0x10F3, 0x10F5
max_keypresses = 8
soft_reset = false

; Do not modify the values below unless you know what you're doing
vcount_range_bw1 = 0x60, 0x60
vcount_range_bw2 = 0x82, 0x82
vframe_range = 0x8, 0x8
gxstat_range = 0x6, 0x6
